language: php

php: 
  - 5.3
  - 5.4
  - 5.5

notifications:
  irc: "irc.freenode.net#masterminds"

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install

script: phpunit test/HTML5