language: php

php: 
  - 5.3
  - 5.4
  - 5.5

notifications:
  irc: "irc.freenode.net#masterminds"

before_script:
  - composer self-update
  - composer install --dev

after_script:
  - php vendor/bin/coveralls -v

script: phpunit test/HTML5