markdown: rdiscount
baseurl: http://masterminds.github.io/html5-php

navigation:
- text: Docs
  url: https://github.com/Masterminds/html5-php/wiki
- text: API
  url: http://masterminds.github.io/html5-php/api/
- text: Github
  url: https://github.com/Masterminds/html5-php
